"""add channel_name and agora_token to appointments

Revision ID: 2bd8dcb790f7
Revises: b9280d1476f4
Create Date: 2025-09-19 19:58:45.347408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bd8dcb790f7'
down_revision: Union[str, Sequence[str], None] = 'b9280d1476f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('channel_name', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('agora_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'agora_token')
    op.drop_column('appointments', 'channel_name')
    # ### end Alembic commands ###
